### ISSUE TITLE
Multi-Resolution Reconstruction

### ISSUE THREAD

**Issue by XiaoWang-Github** [cabouman/svmbir#120]
Hi everyone,

    I tested the python wrapper today. Great work! Thank you everyone! It's very easy to install and use it.

    However, I have concern about demo's image quality. Why are all reconstructions from the demo look blurry? Both microscopy and shepp-logan demos look blurry. The microscopy demo is especially blurry. I have attached my reconstructed image and the original phantom.

    Another concern I have is about MBIR algorithmic convergence.  The 3D microscopy demo takes more than 200 iterations.  Why is the convergence so slow?
   
![3D_microscopy_recon](https://user-images.githubusercontent.com/60047861/99928856-f6528400-2d18-11eb-8341-31affd8e0f28.png)
![3D_microscopy](https://user-images.githubusercontent.com/60047861/99928857-f6528400-2d18-11eb-9924-301e4eb34cbb.png)

**Comment by cabouman** [comment]
In order to make limited angle convergence reasonable, we need to implement multi-resolution reconstruction. We just never observed this before because we couldn't easily do the reconstructions. 

Also, in order to implement the multi-resolution, we first needed to tune the parameter selection (which we have mostly done) so that the regularization didn't change dramatically with resolution. 

But the good news is we are making great progress!!

**Comment by cabouman** [comment]
OK, I got an initial version of multires_recon() working. I put it in the branch named "multi res_dev". You can run the demo named "demo_multires.py" to try it out.

**Comment by sjkisner** [comment]
This is cool! I try this out on the microscopy data.

**Comment by cabouman** [comment]
**Thilo's comments:** 

### *args and **kwargs
The use of *args and **kwargs [link here](https://book.pythontips.com/en/latest/args_and_kwargs.html) would be a way to do this since multires_recon() is very much only a wrapper around recon(). That is, most of the arguments to both functions are the same. Actually I think all arguments are the same except for max_resolutions.
``def multires_recon(max_resolutions, *args, **kwargs):``
In the very bottom of multires_recon() we would not call recon() with all these arguments separately but instead simply call
``reconstruction = recon(*args, **kwargs)``

### How do the resizing operations affect the voxels outside the reconstruction region?
- Due to the interpolation I assume it is likely that the voxels outside will not necessarily stay non-zero. This is something I noticed when writing the multi-resolution code for the cone-beam recon.

### max_resolutions:
- I don't really understand how this parameter works. Is this the maximum depth of the recursion tree? Is there a more intuitive way of doing this, for example with a recursion depth counter or something? Something that is not intuitive enough may be difficult to debug.

### Resizing the sinogram
- in my multi-resolution code I resize both the sonogram and the image. This way the resolution of the recon is always resolution at iso. This makes speeds up the overall computation because there is in general less data (both A and y are smaller). (In this case it is important to scale the center_offset parameter accordingly though.)

**Comment by XiaoWang-Github** [comment]
Sounds good!

**Comment by cabouman** [comment]
Decide that *args, **kwargs wasn't worth it. Will do sinogram resizing in future.
