### ISSUE TITLE
Demo.py script

### ISSUE THREAD

**Issue by XiaoWang-Github** [cabouman/svmbir#14]
why do we need image down sampling in the demo python script?

**Comment by smajee** [comment]
Since the Shepp-Logan phantom has a lot of sharp features, there aren't enough measurements to reconstruct the image well enough at the detector resolution.
But downsampling (voxel size larger than detector pixel size) produces high quality reconstructions.

**Comment by XiaoWang-Github** [comment]
So instead of doing image downsampling, why not giving the users the option to set the voxel size and image size directly?

**Comment by smajee** [comment]
There are some redundancies in setting the voxel size and detector pixel size independently and a new user might get confused.
For example, doubling both voxel size and detector pixel size does not change the geometry and having the ratio of voxel size and detector pixel size to not be an integer is generally not a good idea.
That is why I tried to simplify the parameters to something like 'image downsampling' that is less redundant and is set to 1 by default (like TomoPy).
If the name 'img_downsamp' feels confusing, feel free to suggest alternate names.

**Comment by cabouman** [comment]
OK, now I understand. I like this idea. Maybe we should set the detector pitch, and set a image "image downsampling" factor, and this should generate the pixel pitch. 

The question is, do we allow for downsampling values <1? This would result in interpolation, which is sometimes useful in tomography. Also, do we allow for non-integer values? 

I think the answer should be "yes" in both cases, but perhaps in the manual (to be generated) we should warn people not to do this unless they know what they are doing, and the default value of downsampling should be 1.

**Comment by sjkisner** [comment]
In my opinion I think we should allow the image size to be set independently.  Something that a single "downsampling" value disallows is reconstructing a non-square image.  In some applications, microscopy for example, you may have a very thin sample and requiring a square image means reconstructing many times more pixels than you need to (also a much larger A-matrix).  With the data sets I'm looking at now that could also easily mean there's not enough resources to run the problem.

**Comment by smajee** [comment]
When I started writing the python wrapper I made a design choice to follow the interface of TomoPy.
The advantage of this approach was that the interface was simple for beginers and anyone already using TomoPy can easily switch to svmbir and get a faster reconstruction.
However, this came at the cost of reduced freedom in choosing the geometry settings, which at the time I did not think would be significant for the users.

I feel now that some users do indeed care about or need more freedom in choosing the geometry parameters.
However, enabling this increased freedom while keeping the interface similar to TomoPy will be hard.
Therefore, I think the best way to go would be to have two interfaces.

**Interface 1:** Object oriented interface with methods initialize geometry, reconstruct and forward project
This will allow the user to set all the geometry parameters arbitrarily and there won't be any loss of information when voxel size is bigger than the detector pixel size

**Interface 2:** This would be the current interface that is similar to TomoPy.
However, in order to avoid duplication of code, this interface will call the object oriented interface 1 internally with the geometry parameters set in a simplistic fashion like TomoPy.

Multiple interface are indeed present in some popular open source python packages such as matplotlib.
There is a simplistic functional interface for making simple plots, and another object oriented interface for doing more complicated plots.

**Comment by cabouman** [comment]
Hi all,
I think we need to have a Zoom meeting to discuss our path forward on this.

To me the highest priorities are:
	1) Figuring out the interface to the python wrapper
	2) Getting some preliminary documentation written.

Maybe we can write the documentation first, and then modify the code to comply with it.
That way we will have a clear plan.
If someone can start document for documentation, I can work on it.

Also, I think we can put the Cython development on hold until we get all this figured out.

Charlie

**Comment by cabouman** [comment]
This thread raised good questions, but there is no long any specific problem to solve so I'm closing it.
