### ISSUE TITLE
User argument type bug | Check user arguments

### ISSUE THREAD

**Issue by tbalke** [cabouman/svmbir#20]
When using NumPy types as arguments for the `recon` function the `yaml.dump` command fails when called from the `utils.write_params` routine.

For example, running 
```
offsets = np.array([42])
offset = offsets[0]
x = svmbir.recon(sino, angles, weight, center_offset=offset, [...])
```
where `type(offset)` is `<class 'numpy.int64'>`, the following error message appears:
```
ruamel.yaml.representer.RepresenterError: cannot represent an object: 42
```

This can be patched by first casting to float as in `offset = float(offsets[0])`, although this should be handled automatically in the `recon` function.

I recommend a general check-user-arguments routine. This should check or ensure the type of the argument and whether it is sensible. For example `img_downsample = 1.5` has the wrong type (float) and `img_downsample = -1` is not sensible (should be >=1).

**Comment by smajee** [comment]
I believe the issue is due to a shortcoming of the YAML package as it is designed to only handle pure python data types and not numpy ones.
I think the issue can be solved by adding a recursive check and conversion in the write_params routine.
I will try to patch it later this week.

A general check-user-arguments routine would be useful as well.
But we should add it once we fix the I/O specifications.

**Comment by tbalke** [comment]
Yes, I agree.

I think that `offset.item()` would also work and in general the `item` function should convert it to native Python types (with some exceptions that we can probably ignore).

See [this](https://stackoverflow.com/a/11389998) stackoverflow answer for reference.
