### ISSUE TITLE
Issues in docstring description.

### ISSUE THREAD

**Issue by DamonLee5** [cabouman/svmbir#23]
1.  In recon(), the order of sharpen and sigma_x is different between markdown and doctoring.
2. The order of prox_image and Advanced Parameters: init_image, init_proj are different between markdown and doctoring.
3. object_name cannot find corresponding parameter in macdown.
4. Latex formula should be changed to sphinx math,
From:
$$ {\hat x} = \arg \minx \left{ \frac{1}{2} \Vert y - Ax \Vert\Lambda^2 + \frac{1}{2\sigma_x^2} \Vert x -v \Vert^2 \right} $$ 
To:
.. math::
{\hat x} = \arg \minx \left{ \frac{1}{2} \Vert y - Ax \Vert\Lambda^2 + \frac{1}{2\sigma_x^2} \Vert x -v \Vert^2 \right}

**Comment by DamonLee5** [comment]
In project(),
1. The orders of parameter are different between markdown and doctoring.
2. The parameter object_name corresponding parameter in macdown cannot be found.

**Comment by DamonLee5** [comment]
In _calc_weights(),
1. weights parameter is deleted in the docstring.
2. Exception: Description needed.
For other functions, some types of parameters are not listed.

**Comment by smajee** [comment]
There are several differences between the reference documentation in docs/reference and the current interface, namely:
- Renaming certain input params (e.g.: num_col->num_cols, num_row->num_rows etc) to make it fit with the existing code conventions
- Removing certain input params (e.g.: removing weights input from cal_weights since it was not needed)
- Adding certain input params (e.g. adding object_name to recon and project in order to provide hooks for building multi-process and multi-node functionality).

These differences are there by design and we should not change the code to fit the reference markdown documentation.
We should not also try to change the reference markdown documentation to be in sync with the code since we plan to remove the markdown documentation anyway once we generate html documentation from the python doc-strings using sphinx.

However, we should make the python doc-strings in sync with the code (which now it is) and make sure to update it if we change the interface further.
