### ISSUE TITLE
Blurry Demo Reconstructions 

### ISSUE THREAD

**Issue by XiaoWang-Github** [cabouman/svmbir#240]
Both the 2D and 3D Shepp Logan as well as microscopy demo reconstructions look blurry.  See the attached images.  Are the prior parameters set wrong?

![3d_shepp_logan_recon](https://user-images.githubusercontent.com/60047861/166132814-4b99447e-dee3-43b7-80c0-50748fdc2a81.png)
![3D_microscopy_recon](https://user-images.githubusercontent.com/60047861/166132818-7611a7db-6cf2-41f5-a893-63892c8d1823.png)
![2D_microscopy_recon](https://user-images.githubusercontent.com/60047861/166132821-d574a153-5ba3-4a31-b47a-2dc0c0bc237d.png)

**Comment by cabouman** [comment]
Xiao, the microscopy recon is always going to be a little blurry due to the limited data.
However, I agree that, on average, the recons tend to be a bit over regularized.
This is closely related to the issue #239, which recommends reducing "regularization" for the proximal map mode.

I propose we try two changes in the prerelease branch that address both problems consistently.
In `auto_sigma_x` we can change the scaling factor to `0.3` so that:

> `return_ 0.3 * auto_sigma_prior(sino, delta_channel, sharpness)`

And in In `auto_sigma_p` we can change the scaling factor to `2.0` so that:
> `return 2.0 * auto_sigma_prior(sino, delta_channel, sharpness)`

There could be some backward compatibility issues, but I think it's better to pull the bandaid off now. 
If this is agreeable to everyone, I can make the changes, and then you can try running the new code to see if you like it better.

**Comment by XiaoWang-Github** [comment]
Sounds good!

**Comment by cabouman** [comment]
I had an extensive discussion with Jordan about this, and I'm talking to different people to formulate the best solution. This is a very small change, but it needs to be done very carefully.

**Comment by cabouman** [comment]
OK, my solution to this problem was just to increase the value of sharpness in the demos.
In the future, we may want to increase the default sharpness values in the code.
