### ISSUE TITLE
Compilation issue with mac gcc fail.

### ISSUE THREAD

**Issue by DamonLee5** [cabouman/svmbir#38]

**Comment by sjkisner** [comment]
Any details?  I think Thilo compiles with gcc on a mac.

**Comment by cabouman** [comment]
Wenrui, What problem are you having compiling on a Mac? Are you going to fix this?

**Comment by smajee** [comment]
It may not be clear from the description, but the issue is that since in macos gcc 'points-to' clang and some users may not know about this, they might try to run the gcc make command in mac instead of clang. This will most likely lead to an error. 

One way to solve it is to put more detailed instructions so that the user does not do this in macs.

The other way is to make the whole process automatic, so that the user does not have to worry about what commands to run for which system to compile the code. We were discussing this in the code review and it turned out to be a harder problem than we initially thought. The preliminary plan of action is to first try doing this for a sandbox repository. However, we do not yet have a more detailed plan about what needs to be done to do the automated compilation.

**Comment by cabouman** [comment]
I added a section to the overview explain this issue to users. I think this should be enough for now.
