### ISSUE TITLE
Order of variables and functions

### ISSUE THREAD

**Issue by tbalke** [cabouman/svmbir#39]
While reading the docs I found that the order of functions listed and the arguments could be improved.

The functions seem to be in alphabetical order (first auto_sigma_x, last recon). Can this be changed in the sphinx settings?
I think it would make more sense to put the most important functions first (recon, project) and also group the roughly semantically.

The optional arguments seem a little out of whack, too. 
For example we have "sigma_x=None, sharpen=1.0, positivity=True, p=1.2, q=2.0, T=1.0" which breaks apart the sigma_x from the rest of the q-GGMRF parameters, while positivity does not fit into the mix.
In general I would suggest the same paradigm: sort by priority/significance and roughly group semantically.

Thilo

**Comment by smajee** [comment]
In my opinion the parameters are for the most part already organized semantically and in order of importance. There is of course some room for disagreement because it is subjective by nature. For example, the parameters you listed are together because they all relate to the prior model. They are ordered by importance to the user. A typical user would mostly change sigma_x/sharpen and that is why they are at the beginning. On the other hand, since most users will not change the p, q, T parameters at all, they are at the end.

However, I do agree that in the documentation, the important functions like recon and project needs to come before the utility functions like auto_sigma_x. We should investigate how to do that.

**Comment by smajee** [comment]
I think, we may be able to change the order of the functions in the docs by changing the __all__ variable in the package __init__.py file.

**Comment by tbalke** [comment]
Ok, great. I agree.

But in my opinion,  "positivity=True, sharpen=1.0, sigma_x=None, p=1.2, T=1.0, q=2.0" would still make more sense because it keeps the mrf parameters grouped.

Thilo

**Comment by bwohlberg** [comment]
> The functions seem to be in alphabetical order (first auto_sigma_x, last recon). Can this be changed in the sphinx settings?
> I think it would make more sense to put the most important functions first (recon, project) and also group the roughly semantically.

The order of the functions in the docs can be set to follow the order in the source file by adding
```
autodoc_member_order = 'bysource'
```
to the sphinx `conf.py`.

> The optional arguments seem a little out of whack, too.
> For example we have "sigma_x=None, sharpen=1.0, positivity=True, p=1.2, q=2.0, T=1.0" which breaks apart the sigma_x from the rest of the q-GGMRF parameters, while positivity does not fit into the mix.
> In general I would suggest the same paradigm: sort by priority/significance and roughly group semantically.

I'm not sure I understand this. Are you saying that sphinx is re-ordering the function parameter lists, or that the parameter lists in the source need to be changed?

**Comment by tbalke** [comment]
Brendt,

Thanks for your comments.

The order of the functions in the docs can be set to follow the order in
the source file by adding

autodoc_member_order = 'bysource'

Yes, this is just what we want.

I'm not sure I understand this. Are you saying that sphinx is re-ordering
the function parameter lists, or that the parameter lists in the source
need to be changed?


It is the parameter list in the source. So sphinx is not the issue.

Thilo

**Comment by cabouman** [comment]
I think what we have is probably good enough for now. I'm going to close this issue.
