### ISSUE TITLE
Multiple README files

### ISSUE THREAD

**Issue by bwohlberg** [cabouman/svmbir#46]
The repo currently has both `README.md` and `README.rst` files. One of these should be removed.

**Comment by cabouman** [comment]
Does the ``README.rst`` file currently do anything?

**Comment by DamonLee5** [comment]
README.rst under root folder should be deleted. I moved it to docs folder
previously to serve as part of index.

I will remove it now.

Best,
Wenrui

Charles A Bouman <notifications@github.com> 于2020年11月5日周四 下午6:41写道：

**Comment by DamonLee5** [comment]
I deleted README.rst directly in the master branch. Also, I add "pip
install update" in install.rst in the master branch too.

Since I update this in the master branch and I am sure that I did not break
the code, I think you can close that issue.

Best,
Wenrui

Damon Li <liwr5damon@gmail.com> 于2020年11月5日周四 下午6:46写道：
