### ISSUE TITLE
Parameter exception handling

### ISSUE THREAD

**Issue by sjkisner** [cabouman/svmbir#50]
From how the package has evolved, we have reconparam defaults that look to be defined in 2 places.

Since almost all the recon defaults are defined within `recon()` now, I suggest we do away with `_default_reconparams` dictionary at the top of svmbir.py to avoid confusion and assemble the reconparams dictionary in a similar manner to sinoparams and imgparams.

**Comment by cabouman** [comment]
Let's use this issue to continue the conversation of how to best set any required parameter defaults.

**Comment by sjkisner** [comment]
@smajee Currently the weights are always constructed by python so the weightType parameter isn't used by the c-code.  Although this results in some extra I/O I think it's simplest to leave it this way for now.  The weights are currently used by python in auto_sigma_y(), so there's potential for introducing a bug if the weights aren't exactly the same in python and the C routines.

**Comment by cabouman** [comment]
I think we need to go through the code and redo or remove the unused defaults, and put in exception handling for all parameters.

Wenrui, perhaps you can talk to Soumendu about how to do this.
Then make **small** changes, and pass them by reviewers when doing pull requests.

**Comment by DamonLee5** [comment]
> I think we need to go through the code and redo or remove the unused defaults, and put in exception handling for all parameters.
> 
> Wenrui, perhaps you can talk to Soumendu about how to do this.
> Then make **small** changes, and pass them by reviewers when doing pull requests.

I have talked to Soumendu and made a pull request to clean up the default parameter.

**Comment by cabouman** [comment]
OK, that's good.

Now we need to add exception handling for the parameters.
We need to check that all incoming parameters are in the correct ranges and values.
Maybe we can do this a little bit at a time.

**Comment by cabouman** [comment]
We need to bound check the array sizes. Something like adjusting the image size if

``delta_pixel*max(num_rows+2,num_cols+2)*sqrt(2) > delta_channel*(num_channels+2*channel_offset)``

**Comment by DamonLee5** [comment]
I think I misunderstood what I should do.

Now, we want to check if the parameter is in a valid range and then **fix** it. 

The plan will be,

if p<1 or p>2:
print(Parameter p() is not in the valid range [1,2]) 
p=1

if q<1 or q>2:
print(Parameter q() is not in the valid range [1,2]) 
q=2

if p>q:
print(Parameter q() cannot be greater than parameter p())
p=q

For this plan, I still want to confirm 2 things.
(1) Should we handle p<1 and p>2 separately?  
We can print out different messages for these 2 situations instead of saying they are not in the valid range.

(2) Should we use warnings instead of print? For example,
```
import warnings
warnings.warn("Warning...........Message")
```

**Comment by smajee** [comment]
I don't know what is the most standard way to do these things (set default value in case of failure) but using the warnings package sounds much better than printing the warning.

**Comment by cabouman** [comment]
We should set up a function to do the testing so that that we don't have lots of junk in svmbir.py. The function should do something like. The function can be located in _utils.py .

>def _test_pq_values(p,q)
> if q<1 or q>2:
>warnings.warn("Parameter q not in the valid range of [1,2]; Setting q=2.")
>q=2
>
>if p<1 :
>warnings.warn("Parameter p<1; Setting p=1.")
>p=1
>
>if p>2:
>warnings.warn("Parameter p>2; Setting p=2.")
>p=2
>
>if p>q:
>warnings.warn("Parameter p>q; Setting p=q.")
>p=q
>
>return p, q`

**Comment by cabouman** [comment]
Soumendu, this is good, but make sure you add a doc string to any new function you add.

Please do something similar with the other error checking.

**Comment by smajee** [comment]
Understood, but I believe @DamonLee5 wrote the parameter checking function which you are probably talking about.

I will make sure to add docstrings if/when I add new functions to svmbir.

**Comment by DamonLee5** [comment]
> Soumendu, this is good, but make sure you add a doc string to any new function you add.
> 
> Please do something similar with the other error checking.

Understood, I did not add a doc string since I noticed that other functions in _utils.py did not have doc string. 

I will add a doc string when I add new functions to svmbir.

**Comment by DamonLee5** [comment]
# Plan to handle parameters of recon()
My next step will continue handling parameter exceptions in recon(). Since there are many parameters for recon(), I try to group them together based on their data types. So I can update them group-by-group.

Section 1.5 lists the parameters I want to confirm their range and how to fix.

## 1. scalar. 
Give a warning if it is some string or list and set to the default value.

### 1.1 Float, Range (-inf, inf)
- center_offset (float, optional) – [Default=0.0] Scalar value of offset from center-of-rotation.
- init_image (float, optional) – [Default=0.0] Initial value of reconstruction image, specified by either a scalar value or a 3D numpy array with shape (num_slices,num_rows,num_cols).
- init_proj (None, optional) – [Default=None] Initial value of forward projection of the init_image. This can be used to reduce computation for the first iteration when using the proximal map option.

### 1.2 Float, Positive, Range (0, inf)
If it is out of valid range, set to default or automatically set.
- delta_channel (float, optional) – [Default=1.0] Scalar value of detector channel spacing in 𝐴𝐿𝑈.
- delta_pixel (float, optional) – [Default=1.0] Scalar value of the spacing between image pixels in the 2D slice plane in 𝐴𝐿𝑈.
- roi_radius (float, optional) – [Default=None] Scalar value of radius of reconstruction in 𝐴𝐿𝑈. If None, automatically set.

### 1.3 Float, Range [0,1)
If it is out of valid range, set to default or automatically set.
- stop_threshold (float, optional) – [Default=0.01] Scalar valued stopping threshold in percent. If stop_threshold=0, then run max iterations.

### 1.4 Integer, Positive.
If it is less or equal to 0, set to the default value. If it is positive but not an integer, use int() to fix it. 
- num_rows (int, optional) – [Default=None] Integer number of rows in reconstructed image. If None, automatically set.
- num_cols (int, optional) – [Default=None] Integer number of columns in reconstructed image. If None, automatically set.
- max_iterations (int, optional) – [Default=100] Integer valued specifying the maximum number of iterations.
- num_threads (int, optional) – [Default=None] Number of compute threads requested when executed. If None, num_threads is set to the number of cores in the system

### 1.5 Range I don't know. I believe there will be a stricter range than general (0, inf) or (-inf, inf)
- sigma_y (float, optional) – [Default=None] Scalar value of noise standard deviation parameter. If None, automatically set.
- snr_db (float, optional) – [Default=30.0] Scalar value that controls assumed signal-to-noise ratio of the data in dB. Ignored if sigma_y is not None.
- sigma_x (float, optional) – [Default=None] Scalar value >0 that specifies the qGGMRF scale parameter. If None, automatically set by calling svmbir.auto_sigma_x. The parameter sigma_x can be used to directly control regularization, but this is only recommended for expert users.
- sharpness (float, optional) – [Default=0.0] Scalar value that controls level of sharpness. sharpness=0 is neutral; sharpness>0 increases sharpness; sharpness<0 reduces sharpness. Ignored if sigma_x is not None.
- T (float, optional) – [Default=1.0] Scalar value >0 that specifies the qGGMRF threshold parameter.
- b_interslice (float, optional) – [Default=1.0] Scalar value >0 that specifies the interslice regularization. The default values of 1 should be fine for most applications. However, b_interslice can be increased to values >1 in order to increase regularization along the slice axis.
- num_threads (int, optional) – If it is too large, it will also affect the performance. Maybe we should calculate the range based on the number of cores.

## 2. The value should be in a specific list.
If the value is not in the specific list, give a warning, and set it to default.
- weight_type (string, optional) – [Default=”unweighted”] Type of noise model used for data.  
[“unweighted”,  “transmission”, “transmission_root”,  “emmission”]
- verbose (int, optional) – [Default=1] Possible values are {0,1,2}, where 0 is quiet, 1 prints minimal reconstruction progress information, and 2 prints the full information.

## 3. Bool
We should make sure it is Bool and give a warning when it is not True or False.
- positivity (bool, optional) – [Default=True] Boolean value that determines if positivity constraint is enforced. The positivity parameter defaults to True; however, it should be changed to False when used in applications that can generate negative image values.
- delete_temps (bool, optional) – [Default=True] Delete temporary files used in computation.

## 4. Array
Check the shape of the array. Array shape is hard to fix. I think the only way is to raise an error.
- sino (float) – 3D numpy array of sinogram data with shape (num_views,num_slices,num_channels)
- weights (ndarray, optional) – [Default=None] 3D numpy array of weights with same shape as sino.
The shape of sino and weights should be the same. 

- angles (float) – 1D numpy array of view angles in radians.

- prox_image (ndarray, optional) – [Default=None] 3D numpy array with proximal map input image. If prox_image is supplied, then the proximal map prior model is used, and the qGGMRF parameters are ignored.
prox_image have the same shape as reconstruction image (num_slices,num_rows,num_cols).

## 5. string
I guess we don't need to handle the string parameter exception. 
- svmbir_lib_path (string, optional) – [Default=~/.cache/svmbir/parbeam] Path to directory containing library of forward projection matrices.
- object_name (string, optional) – [Default=’object’] Specifies filenames of cached files. Can be changed suitably for running multiple instances of reconstructions. Useful for building multi-process and multi-node functionality on top of svmbir.

**Comment by sjkisner** [comment]
In the `test_parameter_line*` functions, most scalar parameter inputs are rejected unless they're specifically given as floats, e.g. `sharpness=1.0` works, `sharpness=1 `doesn't work.  Do we want to allow integer types for these?

I'm at least fixing the documentation because a few parameter descriptions show examples where a float parameter is specified in integer form (`sharpness`, for example).

**Comment by sjkisner** [comment]
I think we can close this issue on the arguments testing. Updates to these functions are in for the next release.
