### ISSUE TITLE
Improve sigma_x and sigma_y calculations

### ISSUE THREAD

**Issue by cabouman** [cabouman/svmbir#52]
The current calculations of sigma_x and sigma_y behave badly in some cases when there are many zeros in the reconstruction. We can use the following to improve the automatic values:

**For sigma_y creations:**
indicator = np.int8(sino > 0.05*np.average(np.absolute(sino)) )
signal_rms = np.average(weights * sino**2, None, indicator)**0.5
rel_noise_std = 10**(-snr_db/20)
sigma_y = rel_noise_std * signal_rms

**For sigma_x creations:**
indicator = np.int8(sino > 0.05*np.average(np.absolute(sino)) )
sigma_x = 0.1 * sharpen * np.average(sino,weights=indicator) / (num_channels*delta_channel)

**Comment by sjkisner** [comment]
I added the modifications.  I used np.fabs() over np.absolute() since we don't need to accommodate complex values, and I used np.mean() for the average where we're not applying the Indicator.

With the change, the default demo result (sharpen=1) looks like a better default for the regularization.  It also converges more fully in 20 iterations, where previously you could still see the SVs unless you ran more like 30 iterations.
