### ISSUE TITLE
Paths in demo file

### ISSUE THREAD

**Issue by svvenkatakrishnan** [cabouman/svmbir#83]
Fix paths to sinogram data in the demo files so that it takes care of relative paths i.e. python demo/demo_complex.py runs without errors.

**Comment by cabouman** [comment]
Vankat, we redid all the demo files, and we removed the sinogram data. So hopefully, the bug is fixed.

**Comment by smajee** [comment]
I don't think the issue is completely fixed yet.
The demo writes images into the output directory which does not exist if it is run from outside the demo directory and it leads to errors.

The demo should either write the images to the current directory or create the output directory before writing the output images.

**Comment by cabouman** [comment]
OK, can you fix it by adding a command to create the directory?

**Comment by sjkisner** [comment]
Also the phantom.plot_image() function that is doing this writing needs to handle the "optional" arguments appropriately.  It currently crashes if you leave any of the optional arguments off.

This function can also try/except for the "writeability" of the specified output file so that it fails more gracefully.

**Comment by cabouman** [comment]
Jordan, you understand this better than I do. 
Can you fix it, and I will look at the fix so I know how to do it in the future?

**Comment by smajee** [comment]
Although I fixed the bug by updating the demos, I think it would be more elegant if the phantom.plot_image always creates the output folder before writing the images.

**Comment by sjkisner** [comment]
I fixed the defaults handling in phantom.plot_image().  Turns out the only thing that would fail is if you left the filename off, or if the file can't be opened for writing. Now it only tries to write if the filename argument is given, and it exits with a warning if the file can't be opened for writing.

It's possible to have plot_image() create a directory if it doesn't exist, but it still needs the exception handling because it might try to write somewhere that isn't writable.
